server:
  port: 8080

spring: 
  application.name: gateway
  cloud:
    gateway:
      discovery:
        # The service ID of the service to which the gateway routes requests
        locator:
          # make sure a DicoveryClient implementation is available(Netflix Eureka, Consul, Zookeeper, Kubernetes, etc.) available in the classpath
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # The hostname of the instance. If not specified, the IP address of the instance is used.
    prefer-ip-address: true 


management:
  endpoints:
    web:
      exposure:
        include: "*"